// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"patient/ent/examinedetail"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ExamineDetail is the model entity for the ExamineDetail schema.
type ExamineDetail struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExamineDetail) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case examinedetail.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExamineDetail fields.
func (ed *ExamineDetail) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case examinedetail.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ed.ID = int(value.Int64)
		default:
			ed.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExamineDetail.
// This includes values selected through modifiers, order, etc.
func (ed *ExamineDetail) Value(name string) (ent.Value, error) {
	return ed.selectValues.Get(name)
}

// Update returns a builder for updating this ExamineDetail.
// Note that you need to call ExamineDetail.Unwrap() before calling this method if this ExamineDetail
// was returned from a transaction, and the transaction was committed or rolled back.
func (ed *ExamineDetail) Update() *ExamineDetailUpdateOne {
	return NewExamineDetailClient(ed.config).UpdateOne(ed)
}

// Unwrap unwraps the ExamineDetail entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ed *ExamineDetail) Unwrap() *ExamineDetail {
	_tx, ok := ed.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExamineDetail is not a transactional entity")
	}
	ed.config.driver = _tx.drv
	return ed
}

// String implements the fmt.Stringer.
func (ed *ExamineDetail) String() string {
	var builder strings.Builder
	builder.WriteString("ExamineDetail(")
	builder.WriteString(fmt.Sprintf("id=%v", ed.ID))
	builder.WriteByte(')')
	return builder.String()
}

// ExamineDetails is a parsable slice of ExamineDetail.
type ExamineDetails []*ExamineDetail
