// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"patient/ent/inpatient"
	"patient/ent/patient"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Inpatient is the model entity for the Inpatient schema.
type Inpatient struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// PatientID holds the value of the "patient_id" field.
	PatientID uuid.UUID `json:"patient_id,omitempty"`
	// RegisterDate holds the value of the "register_date" field.
	RegisterDate time.Time `json:"register_date,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InpatientQuery when eager-loading is set.
	Edges        InpatientEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InpatientEdges holds the relations/edges for other nodes in the graph.
type InpatientEdges struct {
	// Patient holds the value of the patient edge.
	Patient *Patient `json:"patient,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PatientOrErr returns the Patient value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InpatientEdges) PatientOrErr() (*Patient, error) {
	if e.Patient != nil {
		return e.Patient, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: patient.Label}
	}
	return nil, &NotLoadedError{edge: "patient"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Inpatient) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case inpatient.FieldRegisterDate:
			values[i] = new(sql.NullTime)
		case inpatient.FieldID, inpatient.FieldPatientID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Inpatient fields.
func (i *Inpatient) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for j := range columns {
		switch columns[j] {
		case inpatient.FieldID:
			if value, ok := values[j].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[j])
			} else if value != nil {
				i.ID = *value
			}
		case inpatient.FieldPatientID:
			if value, ok := values[j].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field patient_id", values[j])
			} else if value != nil {
				i.PatientID = *value
			}
		case inpatient.FieldRegisterDate:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field register_date", values[j])
			} else if value.Valid {
				i.RegisterDate = value.Time
			}
		default:
			i.selectValues.Set(columns[j], values[j])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Inpatient.
// This includes values selected through modifiers, order, etc.
func (i *Inpatient) Value(name string) (ent.Value, error) {
	return i.selectValues.Get(name)
}

// QueryPatient queries the "patient" edge of the Inpatient entity.
func (i *Inpatient) QueryPatient() *PatientQuery {
	return NewInpatientClient(i.config).QueryPatient(i)
}

// Update returns a builder for updating this Inpatient.
// Note that you need to call Inpatient.Unwrap() before calling this method if this Inpatient
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Inpatient) Update() *InpatientUpdateOne {
	return NewInpatientClient(i.config).UpdateOne(i)
}

// Unwrap unwraps the Inpatient entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (i *Inpatient) Unwrap() *Inpatient {
	_tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Inpatient is not a transactional entity")
	}
	i.config.driver = _tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Inpatient) String() string {
	var builder strings.Builder
	builder.WriteString("Inpatient(")
	builder.WriteString(fmt.Sprintf("id=%v, ", i.ID))
	builder.WriteString("patient_id=")
	builder.WriteString(fmt.Sprintf("%v", i.PatientID))
	builder.WriteString(", ")
	builder.WriteString("register_date=")
	builder.WriteString(i.RegisterDate.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Inpatients is a parsable slice of Inpatient.
type Inpatients []*Inpatient
