// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"patient/ent/medicalhistories"
	"patient/ent/medicalprescription"
	"patient/ent/predicate"
	"patient/ent/prescriptionmedication"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MedicalPrescriptionQuery is the builder for querying MedicalPrescription entities.
type MedicalPrescriptionQuery struct {
	config
	ctx                        *QueryContext
	order                      []medicalprescription.OrderOption
	inters                     []Interceptor
	predicates                 []predicate.MedicalPrescription
	withMedicalHistories       *MedicalHistoriesQuery
	withPrescriptionMedication *PrescriptionMedicationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MedicalPrescriptionQuery builder.
func (mpq *MedicalPrescriptionQuery) Where(ps ...predicate.MedicalPrescription) *MedicalPrescriptionQuery {
	mpq.predicates = append(mpq.predicates, ps...)
	return mpq
}

// Limit the number of records to be returned by this query.
func (mpq *MedicalPrescriptionQuery) Limit(limit int) *MedicalPrescriptionQuery {
	mpq.ctx.Limit = &limit
	return mpq
}

// Offset to start from.
func (mpq *MedicalPrescriptionQuery) Offset(offset int) *MedicalPrescriptionQuery {
	mpq.ctx.Offset = &offset
	return mpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mpq *MedicalPrescriptionQuery) Unique(unique bool) *MedicalPrescriptionQuery {
	mpq.ctx.Unique = &unique
	return mpq
}

// Order specifies how the records should be ordered.
func (mpq *MedicalPrescriptionQuery) Order(o ...medicalprescription.OrderOption) *MedicalPrescriptionQuery {
	mpq.order = append(mpq.order, o...)
	return mpq
}

// QueryMedicalHistories chains the current query on the "medical_histories" edge.
func (mpq *MedicalPrescriptionQuery) QueryMedicalHistories() *MedicalHistoriesQuery {
	query := (&MedicalHistoriesClient{config: mpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(medicalprescription.Table, medicalprescription.FieldID, selector),
			sqlgraph.To(medicalhistories.Table, medicalhistories.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, medicalprescription.MedicalHistoriesTable, medicalprescription.MedicalHistoriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(mpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPrescriptionMedication chains the current query on the "prescription_medication" edge.
func (mpq *MedicalPrescriptionQuery) QueryPrescriptionMedication() *PrescriptionMedicationQuery {
	query := (&PrescriptionMedicationClient{config: mpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(medicalprescription.Table, medicalprescription.FieldID, selector),
			sqlgraph.To(prescriptionmedication.Table, prescriptionmedication.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, medicalprescription.PrescriptionMedicationTable, medicalprescription.PrescriptionMedicationColumn),
		)
		fromU = sqlgraph.SetNeighbors(mpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MedicalPrescription entity from the query.
// Returns a *NotFoundError when no MedicalPrescription was found.
func (mpq *MedicalPrescriptionQuery) First(ctx context.Context) (*MedicalPrescription, error) {
	nodes, err := mpq.Limit(1).All(setContextOp(ctx, mpq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{medicalprescription.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mpq *MedicalPrescriptionQuery) FirstX(ctx context.Context) *MedicalPrescription {
	node, err := mpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MedicalPrescription ID from the query.
// Returns a *NotFoundError when no MedicalPrescription ID was found.
func (mpq *MedicalPrescriptionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mpq.Limit(1).IDs(setContextOp(ctx, mpq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{medicalprescription.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mpq *MedicalPrescriptionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := mpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MedicalPrescription entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MedicalPrescription entity is found.
// Returns a *NotFoundError when no MedicalPrescription entities are found.
func (mpq *MedicalPrescriptionQuery) Only(ctx context.Context) (*MedicalPrescription, error) {
	nodes, err := mpq.Limit(2).All(setContextOp(ctx, mpq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{medicalprescription.Label}
	default:
		return nil, &NotSingularError{medicalprescription.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mpq *MedicalPrescriptionQuery) OnlyX(ctx context.Context) *MedicalPrescription {
	node, err := mpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MedicalPrescription ID in the query.
// Returns a *NotSingularError when more than one MedicalPrescription ID is found.
// Returns a *NotFoundError when no entities are found.
func (mpq *MedicalPrescriptionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mpq.Limit(2).IDs(setContextOp(ctx, mpq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{medicalprescription.Label}
	default:
		err = &NotSingularError{medicalprescription.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mpq *MedicalPrescriptionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := mpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MedicalPrescriptions.
func (mpq *MedicalPrescriptionQuery) All(ctx context.Context) ([]*MedicalPrescription, error) {
	ctx = setContextOp(ctx, mpq.ctx, ent.OpQueryAll)
	if err := mpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MedicalPrescription, *MedicalPrescriptionQuery]()
	return withInterceptors[[]*MedicalPrescription](ctx, mpq, qr, mpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mpq *MedicalPrescriptionQuery) AllX(ctx context.Context) []*MedicalPrescription {
	nodes, err := mpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MedicalPrescription IDs.
func (mpq *MedicalPrescriptionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if mpq.ctx.Unique == nil && mpq.path != nil {
		mpq.Unique(true)
	}
	ctx = setContextOp(ctx, mpq.ctx, ent.OpQueryIDs)
	if err = mpq.Select(medicalprescription.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mpq *MedicalPrescriptionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := mpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mpq *MedicalPrescriptionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mpq.ctx, ent.OpQueryCount)
	if err := mpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mpq, querierCount[*MedicalPrescriptionQuery](), mpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mpq *MedicalPrescriptionQuery) CountX(ctx context.Context) int {
	count, err := mpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mpq *MedicalPrescriptionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mpq.ctx, ent.OpQueryExist)
	switch _, err := mpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mpq *MedicalPrescriptionQuery) ExistX(ctx context.Context) bool {
	exist, err := mpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MedicalPrescriptionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mpq *MedicalPrescriptionQuery) Clone() *MedicalPrescriptionQuery {
	if mpq == nil {
		return nil
	}
	return &MedicalPrescriptionQuery{
		config:                     mpq.config,
		ctx:                        mpq.ctx.Clone(),
		order:                      append([]medicalprescription.OrderOption{}, mpq.order...),
		inters:                     append([]Interceptor{}, mpq.inters...),
		predicates:                 append([]predicate.MedicalPrescription{}, mpq.predicates...),
		withMedicalHistories:       mpq.withMedicalHistories.Clone(),
		withPrescriptionMedication: mpq.withPrescriptionMedication.Clone(),
		// clone intermediate query.
		sql:  mpq.sql.Clone(),
		path: mpq.path,
	}
}

// WithMedicalHistories tells the query-builder to eager-load the nodes that are connected to
// the "medical_histories" edge. The optional arguments are used to configure the query builder of the edge.
func (mpq *MedicalPrescriptionQuery) WithMedicalHistories(opts ...func(*MedicalHistoriesQuery)) *MedicalPrescriptionQuery {
	query := (&MedicalHistoriesClient{config: mpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mpq.withMedicalHistories = query
	return mpq
}

// WithPrescriptionMedication tells the query-builder to eager-load the nodes that are connected to
// the "prescription_medication" edge. The optional arguments are used to configure the query builder of the edge.
func (mpq *MedicalPrescriptionQuery) WithPrescriptionMedication(opts ...func(*PrescriptionMedicationQuery)) *MedicalPrescriptionQuery {
	query := (&PrescriptionMedicationClient{config: mpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mpq.withPrescriptionMedication = query
	return mpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MedicalHistoryID uuid.UUID `json:"medical_history_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MedicalPrescription.Query().
//		GroupBy(medicalprescription.FieldMedicalHistoryID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mpq *MedicalPrescriptionQuery) GroupBy(field string, fields ...string) *MedicalPrescriptionGroupBy {
	mpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MedicalPrescriptionGroupBy{build: mpq}
	grbuild.flds = &mpq.ctx.Fields
	grbuild.label = medicalprescription.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MedicalHistoryID uuid.UUID `json:"medical_history_id,omitempty"`
//	}
//
//	client.MedicalPrescription.Query().
//		Select(medicalprescription.FieldMedicalHistoryID).
//		Scan(ctx, &v)
func (mpq *MedicalPrescriptionQuery) Select(fields ...string) *MedicalPrescriptionSelect {
	mpq.ctx.Fields = append(mpq.ctx.Fields, fields...)
	sbuild := &MedicalPrescriptionSelect{MedicalPrescriptionQuery: mpq}
	sbuild.label = medicalprescription.Label
	sbuild.flds, sbuild.scan = &mpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MedicalPrescriptionSelect configured with the given aggregations.
func (mpq *MedicalPrescriptionQuery) Aggregate(fns ...AggregateFunc) *MedicalPrescriptionSelect {
	return mpq.Select().Aggregate(fns...)
}

func (mpq *MedicalPrescriptionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mpq); err != nil {
				return err
			}
		}
	}
	for _, f := range mpq.ctx.Fields {
		if !medicalprescription.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mpq.path != nil {
		prev, err := mpq.path(ctx)
		if err != nil {
			return err
		}
		mpq.sql = prev
	}
	return nil
}

func (mpq *MedicalPrescriptionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MedicalPrescription, error) {
	var (
		nodes       = []*MedicalPrescription{}
		_spec       = mpq.querySpec()
		loadedTypes = [2]bool{
			mpq.withMedicalHistories != nil,
			mpq.withPrescriptionMedication != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MedicalPrescription).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MedicalPrescription{config: mpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mpq.withMedicalHistories; query != nil {
		if err := mpq.loadMedicalHistories(ctx, query, nodes, nil,
			func(n *MedicalPrescription, e *MedicalHistories) { n.Edges.MedicalHistories = e }); err != nil {
			return nil, err
		}
	}
	if query := mpq.withPrescriptionMedication; query != nil {
		if err := mpq.loadPrescriptionMedication(ctx, query, nodes,
			func(n *MedicalPrescription) { n.Edges.PrescriptionMedication = []*PrescriptionMedication{} },
			func(n *MedicalPrescription, e *PrescriptionMedication) {
				n.Edges.PrescriptionMedication = append(n.Edges.PrescriptionMedication, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mpq *MedicalPrescriptionQuery) loadMedicalHistories(ctx context.Context, query *MedicalHistoriesQuery, nodes []*MedicalPrescription, init func(*MedicalPrescription), assign func(*MedicalPrescription, *MedicalHistories)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*MedicalPrescription)
	for i := range nodes {
		fk := nodes[i].MedicalHistoryID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(medicalhistories.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "medical_history_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (mpq *MedicalPrescriptionQuery) loadPrescriptionMedication(ctx context.Context, query *PrescriptionMedicationQuery, nodes []*MedicalPrescription, init func(*MedicalPrescription), assign func(*MedicalPrescription, *PrescriptionMedication)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*MedicalPrescription)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(prescriptionmedication.FieldPrescriptionID)
	}
	query.Where(predicate.PrescriptionMedication(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(medicalprescription.PrescriptionMedicationColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PrescriptionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "prescription_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (mpq *MedicalPrescriptionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mpq.querySpec()
	_spec.Node.Columns = mpq.ctx.Fields
	if len(mpq.ctx.Fields) > 0 {
		_spec.Unique = mpq.ctx.Unique != nil && *mpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mpq.driver, _spec)
}

func (mpq *MedicalPrescriptionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(medicalprescription.Table, medicalprescription.Columns, sqlgraph.NewFieldSpec(medicalprescription.FieldID, field.TypeUUID))
	_spec.From = mpq.sql
	if unique := mpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mpq.path != nil {
		_spec.Unique = true
	}
	if fields := mpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, medicalprescription.FieldID)
		for i := range fields {
			if fields[i] != medicalprescription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if mpq.withMedicalHistories != nil {
			_spec.Node.AddColumnOnce(medicalprescription.FieldMedicalHistoryID)
		}
	}
	if ps := mpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mpq *MedicalPrescriptionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mpq.driver.Dialect())
	t1 := builder.Table(medicalprescription.Table)
	columns := mpq.ctx.Fields
	if len(columns) == 0 {
		columns = medicalprescription.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mpq.sql != nil {
		selector = mpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mpq.ctx.Unique != nil && *mpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mpq.predicates {
		p(selector)
	}
	for _, p := range mpq.order {
		p(selector)
	}
	if offset := mpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MedicalPrescriptionGroupBy is the group-by builder for MedicalPrescription entities.
type MedicalPrescriptionGroupBy struct {
	selector
	build *MedicalPrescriptionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mpgb *MedicalPrescriptionGroupBy) Aggregate(fns ...AggregateFunc) *MedicalPrescriptionGroupBy {
	mpgb.fns = append(mpgb.fns, fns...)
	return mpgb
}

// Scan applies the selector query and scans the result into the given value.
func (mpgb *MedicalPrescriptionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mpgb.build.ctx, ent.OpQueryGroupBy)
	if err := mpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MedicalPrescriptionQuery, *MedicalPrescriptionGroupBy](ctx, mpgb.build, mpgb, mpgb.build.inters, v)
}

func (mpgb *MedicalPrescriptionGroupBy) sqlScan(ctx context.Context, root *MedicalPrescriptionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mpgb.fns))
	for _, fn := range mpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mpgb.flds)+len(mpgb.fns))
		for _, f := range *mpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MedicalPrescriptionSelect is the builder for selecting fields of MedicalPrescription entities.
type MedicalPrescriptionSelect struct {
	*MedicalPrescriptionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mps *MedicalPrescriptionSelect) Aggregate(fns ...AggregateFunc) *MedicalPrescriptionSelect {
	mps.fns = append(mps.fns, fns...)
	return mps
}

// Scan applies the selector query and scans the result into the given value.
func (mps *MedicalPrescriptionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mps.ctx, ent.OpQuerySelect)
	if err := mps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MedicalPrescriptionQuery, *MedicalPrescriptionSelect](ctx, mps.MedicalPrescriptionQuery, mps, mps.inters, v)
}

func (mps *MedicalPrescriptionSelect) sqlScan(ctx context.Context, root *MedicalPrescriptionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mps.fns))
	for _, fn := range mps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
