// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"patient/ent/medicationeffect"
	"patient/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MedicationEffectDelete is the builder for deleting a MedicationEffect entity.
type MedicationEffectDelete struct {
	config
	hooks    []Hook
	mutation *MedicationEffectMutation
}

// Where appends a list predicates to the MedicationEffectDelete builder.
func (med *MedicationEffectDelete) Where(ps ...predicate.MedicationEffect) *MedicationEffectDelete {
	med.mutation.Where(ps...)
	return med
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (med *MedicationEffectDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, med.sqlExec, med.mutation, med.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (med *MedicationEffectDelete) ExecX(ctx context.Context) int {
	n, err := med.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (med *MedicationEffectDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(medicationeffect.Table, sqlgraph.NewFieldSpec(medicationeffect.FieldID, field.TypeInt))
	if ps := med.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, med.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	med.mutation.done = true
	return affected, err
}

// MedicationEffectDeleteOne is the builder for deleting a single MedicationEffect entity.
type MedicationEffectDeleteOne struct {
	med *MedicationEffectDelete
}

// Where appends a list predicates to the MedicationEffectDelete builder.
func (medo *MedicationEffectDeleteOne) Where(ps ...predicate.MedicationEffect) *MedicationEffectDeleteOne {
	medo.med.mutation.Where(ps...)
	return medo
}

// Exec executes the deletion query.
func (medo *MedicationEffectDeleteOne) Exec(ctx context.Context) error {
	n, err := medo.med.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{medicationeffect.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (medo *MedicationEffectDeleteOne) ExecX(ctx context.Context) {
	if err := medo.Exec(ctx); err != nil {
		panic(err)
	}
}
