// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"patient/ent/medicalhistories"
	"patient/ent/medicalsurgery"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// MedicalSurgery is the model entity for the MedicalSurgery schema.
type MedicalSurgery struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// MedicalHistoryID holds the value of the "medical_history_id" field.
	MedicalHistoryID uuid.UUID `json:"medical_history_id,omitempty"`
	// StartDate holds the value of the "start_date" field.
	StartDate time.Time `json:"start_date,omitempty"`
	// EndDate holds the value of the "end_date" field.
	EndDate *time.Time `json:"end_date,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Result holds the value of the "result" field.
	Result string `json:"result,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Fee holds the value of the "fee" field.
	Fee float64 `json:"fee,omitempty"`
	// MainDoctorID holds the value of the "main_doctor_id" field.
	MainDoctorID uuid.UUID `json:"main_doctor_id,omitempty"`
	// SupportDoctorIds holds the value of the "support_doctor_ids" field.
	SupportDoctorIds *string `json:"support_doctor_ids,omitempty"`
	// SupportNurseIds holds the value of the "support_nurse_ids" field.
	SupportNurseIds *string `json:"support_nurse_ids,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy uuid.UUID `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy uuid.UUID `json:"updated_by,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MedicalSurgeryQuery when eager-loading is set.
	Edges        MedicalSurgeryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MedicalSurgeryEdges holds the relations/edges for other nodes in the graph.
type MedicalSurgeryEdges struct {
	// MedicalHistories holds the value of the medical_histories edge.
	MedicalHistories *MedicalHistories `json:"medical_histories,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MedicalHistoriesOrErr returns the MedicalHistories value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MedicalSurgeryEdges) MedicalHistoriesOrErr() (*MedicalHistories, error) {
	if e.MedicalHistories != nil {
		return e.MedicalHistories, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: medicalhistories.Label}
	}
	return nil, &NotLoadedError{edge: "medical_histories"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MedicalSurgery) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case medicalsurgery.FieldFee:
			values[i] = new(sql.NullFloat64)
		case medicalsurgery.FieldName, medicalsurgery.FieldResult, medicalsurgery.FieldDescription, medicalsurgery.FieldSupportDoctorIds, medicalsurgery.FieldSupportNurseIds:
			values[i] = new(sql.NullString)
		case medicalsurgery.FieldStartDate, medicalsurgery.FieldEndDate, medicalsurgery.FieldCreatedAt, medicalsurgery.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case medicalsurgery.FieldID, medicalsurgery.FieldMedicalHistoryID, medicalsurgery.FieldMainDoctorID, medicalsurgery.FieldCreatedBy, medicalsurgery.FieldUpdatedBy:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MedicalSurgery fields.
func (ms *MedicalSurgery) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case medicalsurgery.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ms.ID = *value
			}
		case medicalsurgery.FieldMedicalHistoryID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field medical_history_id", values[i])
			} else if value != nil {
				ms.MedicalHistoryID = *value
			}
		case medicalsurgery.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				ms.StartDate = value.Time
			}
		case medicalsurgery.FieldEndDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_date", values[i])
			} else if value.Valid {
				ms.EndDate = new(time.Time)
				*ms.EndDate = value.Time
			}
		case medicalsurgery.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ms.Name = value.String
			}
		case medicalsurgery.FieldResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value.Valid {
				ms.Result = value.String
			}
		case medicalsurgery.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				ms.Description = value.String
			}
		case medicalsurgery.FieldFee:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fee", values[i])
			} else if value.Valid {
				ms.Fee = value.Float64
			}
		case medicalsurgery.FieldMainDoctorID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field main_doctor_id", values[i])
			} else if value != nil {
				ms.MainDoctorID = *value
			}
		case medicalsurgery.FieldSupportDoctorIds:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field support_doctor_ids", values[i])
			} else if value.Valid {
				ms.SupportDoctorIds = new(string)
				*ms.SupportDoctorIds = value.String
			}
		case medicalsurgery.FieldSupportNurseIds:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field support_nurse_ids", values[i])
			} else if value.Valid {
				ms.SupportNurseIds = new(string)
				*ms.SupportNurseIds = value.String
			}
		case medicalsurgery.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ms.CreatedAt = value.Time
			}
		case medicalsurgery.FieldCreatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value != nil {
				ms.CreatedBy = *value
			}
		case medicalsurgery.FieldUpdatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value != nil {
				ms.UpdatedBy = *value
			}
		case medicalsurgery.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ms.UpdatedAt = value.Time
			}
		default:
			ms.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MedicalSurgery.
// This includes values selected through modifiers, order, etc.
func (ms *MedicalSurgery) Value(name string) (ent.Value, error) {
	return ms.selectValues.Get(name)
}

// QueryMedicalHistories queries the "medical_histories" edge of the MedicalSurgery entity.
func (ms *MedicalSurgery) QueryMedicalHistories() *MedicalHistoriesQuery {
	return NewMedicalSurgeryClient(ms.config).QueryMedicalHistories(ms)
}

// Update returns a builder for updating this MedicalSurgery.
// Note that you need to call MedicalSurgery.Unwrap() before calling this method if this MedicalSurgery
// was returned from a transaction, and the transaction was committed or rolled back.
func (ms *MedicalSurgery) Update() *MedicalSurgeryUpdateOne {
	return NewMedicalSurgeryClient(ms.config).UpdateOne(ms)
}

// Unwrap unwraps the MedicalSurgery entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ms *MedicalSurgery) Unwrap() *MedicalSurgery {
	_tx, ok := ms.config.driver.(*txDriver)
	if !ok {
		panic("ent: MedicalSurgery is not a transactional entity")
	}
	ms.config.driver = _tx.drv
	return ms
}

// String implements the fmt.Stringer.
func (ms *MedicalSurgery) String() string {
	var builder strings.Builder
	builder.WriteString("MedicalSurgery(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ms.ID))
	builder.WriteString("medical_history_id=")
	builder.WriteString(fmt.Sprintf("%v", ms.MedicalHistoryID))
	builder.WriteString(", ")
	builder.WriteString("start_date=")
	builder.WriteString(ms.StartDate.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ms.EndDate; v != nil {
		builder.WriteString("end_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(ms.Name)
	builder.WriteString(", ")
	builder.WriteString("result=")
	builder.WriteString(ms.Result)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(ms.Description)
	builder.WriteString(", ")
	builder.WriteString("fee=")
	builder.WriteString(fmt.Sprintf("%v", ms.Fee))
	builder.WriteString(", ")
	builder.WriteString("main_doctor_id=")
	builder.WriteString(fmt.Sprintf("%v", ms.MainDoctorID))
	builder.WriteString(", ")
	if v := ms.SupportDoctorIds; v != nil {
		builder.WriteString("support_doctor_ids=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ms.SupportNurseIds; v != nil {
		builder.WriteString("support_nurse_ids=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ms.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", ms.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", ms.UpdatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ms.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MedicalSurgeries is a parsable slice of MedicalSurgery.
type MedicalSurgeries []*MedicalSurgery
