// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"patient/ent/medicalhistories"
	"patient/ent/medicalsurgery"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MedicalSurgeryCreate is the builder for creating a MedicalSurgery entity.
type MedicalSurgeryCreate struct {
	config
	mutation *MedicalSurgeryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMedicalHistoryID sets the "medical_history_id" field.
func (msc *MedicalSurgeryCreate) SetMedicalHistoryID(u uuid.UUID) *MedicalSurgeryCreate {
	msc.mutation.SetMedicalHistoryID(u)
	return msc
}

// SetStartDate sets the "start_date" field.
func (msc *MedicalSurgeryCreate) SetStartDate(t time.Time) *MedicalSurgeryCreate {
	msc.mutation.SetStartDate(t)
	return msc
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (msc *MedicalSurgeryCreate) SetNillableStartDate(t *time.Time) *MedicalSurgeryCreate {
	if t != nil {
		msc.SetStartDate(*t)
	}
	return msc
}

// SetEndDate sets the "end_date" field.
func (msc *MedicalSurgeryCreate) SetEndDate(t time.Time) *MedicalSurgeryCreate {
	msc.mutation.SetEndDate(t)
	return msc
}

// SetName sets the "name" field.
func (msc *MedicalSurgeryCreate) SetName(s string) *MedicalSurgeryCreate {
	msc.mutation.SetName(s)
	return msc
}

// SetResult sets the "result" field.
func (msc *MedicalSurgeryCreate) SetResult(s string) *MedicalSurgeryCreate {
	msc.mutation.SetResult(s)
	return msc
}

// SetDescription sets the "description" field.
func (msc *MedicalSurgeryCreate) SetDescription(s string) *MedicalSurgeryCreate {
	msc.mutation.SetDescription(s)
	return msc
}

// SetFee sets the "fee" field.
func (msc *MedicalSurgeryCreate) SetFee(f float64) *MedicalSurgeryCreate {
	msc.mutation.SetFee(f)
	return msc
}

// SetNillableFee sets the "fee" field if the given value is not nil.
func (msc *MedicalSurgeryCreate) SetNillableFee(f *float64) *MedicalSurgeryCreate {
	if f != nil {
		msc.SetFee(*f)
	}
	return msc
}

// SetMainDoctorID sets the "main_doctor_id" field.
func (msc *MedicalSurgeryCreate) SetMainDoctorID(u uuid.UUID) *MedicalSurgeryCreate {
	msc.mutation.SetMainDoctorID(u)
	return msc
}

// SetSupportDoctorIds sets the "support_doctor_ids" field.
func (msc *MedicalSurgeryCreate) SetSupportDoctorIds(s string) *MedicalSurgeryCreate {
	msc.mutation.SetSupportDoctorIds(s)
	return msc
}

// SetSupportNurseIds sets the "support_nurse_ids" field.
func (msc *MedicalSurgeryCreate) SetSupportNurseIds(s string) *MedicalSurgeryCreate {
	msc.mutation.SetSupportNurseIds(s)
	return msc
}

// SetCreatedAt sets the "created_at" field.
func (msc *MedicalSurgeryCreate) SetCreatedAt(t time.Time) *MedicalSurgeryCreate {
	msc.mutation.SetCreatedAt(t)
	return msc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (msc *MedicalSurgeryCreate) SetNillableCreatedAt(t *time.Time) *MedicalSurgeryCreate {
	if t != nil {
		msc.SetCreatedAt(*t)
	}
	return msc
}

// SetCreatedBy sets the "created_by" field.
func (msc *MedicalSurgeryCreate) SetCreatedBy(u uuid.UUID) *MedicalSurgeryCreate {
	msc.mutation.SetCreatedBy(u)
	return msc
}

// SetUpdatedBy sets the "updated_by" field.
func (msc *MedicalSurgeryCreate) SetUpdatedBy(u uuid.UUID) *MedicalSurgeryCreate {
	msc.mutation.SetUpdatedBy(u)
	return msc
}

// SetUpdatedAt sets the "updated_at" field.
func (msc *MedicalSurgeryCreate) SetUpdatedAt(t time.Time) *MedicalSurgeryCreate {
	msc.mutation.SetUpdatedAt(t)
	return msc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (msc *MedicalSurgeryCreate) SetNillableUpdatedAt(t *time.Time) *MedicalSurgeryCreate {
	if t != nil {
		msc.SetUpdatedAt(*t)
	}
	return msc
}

// SetID sets the "id" field.
func (msc *MedicalSurgeryCreate) SetID(u uuid.UUID) *MedicalSurgeryCreate {
	msc.mutation.SetID(u)
	return msc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (msc *MedicalSurgeryCreate) SetNillableID(u *uuid.UUID) *MedicalSurgeryCreate {
	if u != nil {
		msc.SetID(*u)
	}
	return msc
}

// SetMedicalHistoriesID sets the "medical_histories" edge to the MedicalHistories entity by ID.
func (msc *MedicalSurgeryCreate) SetMedicalHistoriesID(id uuid.UUID) *MedicalSurgeryCreate {
	msc.mutation.SetMedicalHistoriesID(id)
	return msc
}

// SetMedicalHistories sets the "medical_histories" edge to the MedicalHistories entity.
func (msc *MedicalSurgeryCreate) SetMedicalHistories(m *MedicalHistories) *MedicalSurgeryCreate {
	return msc.SetMedicalHistoriesID(m.ID)
}

// Mutation returns the MedicalSurgeryMutation object of the builder.
func (msc *MedicalSurgeryCreate) Mutation() *MedicalSurgeryMutation {
	return msc.mutation
}

// Save creates the MedicalSurgery in the database.
func (msc *MedicalSurgeryCreate) Save(ctx context.Context) (*MedicalSurgery, error) {
	msc.defaults()
	return withHooks(ctx, msc.sqlSave, msc.mutation, msc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (msc *MedicalSurgeryCreate) SaveX(ctx context.Context) *MedicalSurgery {
	v, err := msc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (msc *MedicalSurgeryCreate) Exec(ctx context.Context) error {
	_, err := msc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (msc *MedicalSurgeryCreate) ExecX(ctx context.Context) {
	if err := msc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (msc *MedicalSurgeryCreate) defaults() {
	if _, ok := msc.mutation.StartDate(); !ok {
		v := medicalsurgery.DefaultStartDate()
		msc.mutation.SetStartDate(v)
	}
	if _, ok := msc.mutation.Fee(); !ok {
		v := medicalsurgery.DefaultFee
		msc.mutation.SetFee(v)
	}
	if _, ok := msc.mutation.CreatedAt(); !ok {
		v := medicalsurgery.DefaultCreatedAt()
		msc.mutation.SetCreatedAt(v)
	}
	if _, ok := msc.mutation.UpdatedAt(); !ok {
		v := medicalsurgery.DefaultUpdatedAt()
		msc.mutation.SetUpdatedAt(v)
	}
	if _, ok := msc.mutation.ID(); !ok {
		v := medicalsurgery.DefaultID()
		msc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (msc *MedicalSurgeryCreate) check() error {
	if _, ok := msc.mutation.MedicalHistoryID(); !ok {
		return &ValidationError{Name: "medical_history_id", err: errors.New(`ent: missing required field "MedicalSurgery.medical_history_id"`)}
	}
	if _, ok := msc.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "MedicalSurgery.start_date"`)}
	}
	if _, ok := msc.mutation.EndDate(); !ok {
		return &ValidationError{Name: "end_date", err: errors.New(`ent: missing required field "MedicalSurgery.end_date"`)}
	}
	if _, ok := msc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MedicalSurgery.name"`)}
	}
	if v, ok := msc.mutation.Name(); ok {
		if err := medicalsurgery.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MedicalSurgery.name": %w`, err)}
		}
	}
	if _, ok := msc.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "MedicalSurgery.result"`)}
	}
	if _, ok := msc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "MedicalSurgery.description"`)}
	}
	if _, ok := msc.mutation.Fee(); !ok {
		return &ValidationError{Name: "fee", err: errors.New(`ent: missing required field "MedicalSurgery.fee"`)}
	}
	if _, ok := msc.mutation.MainDoctorID(); !ok {
		return &ValidationError{Name: "main_doctor_id", err: errors.New(`ent: missing required field "MedicalSurgery.main_doctor_id"`)}
	}
	if _, ok := msc.mutation.SupportDoctorIds(); !ok {
		return &ValidationError{Name: "support_doctor_ids", err: errors.New(`ent: missing required field "MedicalSurgery.support_doctor_ids"`)}
	}
	if _, ok := msc.mutation.SupportNurseIds(); !ok {
		return &ValidationError{Name: "support_nurse_ids", err: errors.New(`ent: missing required field "MedicalSurgery.support_nurse_ids"`)}
	}
	if _, ok := msc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MedicalSurgery.created_at"`)}
	}
	if _, ok := msc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "MedicalSurgery.created_by"`)}
	}
	if _, ok := msc.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "MedicalSurgery.updated_by"`)}
	}
	if _, ok := msc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MedicalSurgery.updated_at"`)}
	}
	if len(msc.mutation.MedicalHistoriesIDs()) == 0 {
		return &ValidationError{Name: "medical_histories", err: errors.New(`ent: missing required edge "MedicalSurgery.medical_histories"`)}
	}
	return nil
}

func (msc *MedicalSurgeryCreate) sqlSave(ctx context.Context) (*MedicalSurgery, error) {
	if err := msc.check(); err != nil {
		return nil, err
	}
	_node, _spec := msc.createSpec()
	if err := sqlgraph.CreateNode(ctx, msc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	msc.mutation.id = &_node.ID
	msc.mutation.done = true
	return _node, nil
}

func (msc *MedicalSurgeryCreate) createSpec() (*MedicalSurgery, *sqlgraph.CreateSpec) {
	var (
		_node = &MedicalSurgery{config: msc.config}
		_spec = sqlgraph.NewCreateSpec(medicalsurgery.Table, sqlgraph.NewFieldSpec(medicalsurgery.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = msc.conflict
	if id, ok := msc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := msc.mutation.StartDate(); ok {
		_spec.SetField(medicalsurgery.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := msc.mutation.EndDate(); ok {
		_spec.SetField(medicalsurgery.FieldEndDate, field.TypeTime, value)
		_node.EndDate = &value
	}
	if value, ok := msc.mutation.Name(); ok {
		_spec.SetField(medicalsurgery.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := msc.mutation.Result(); ok {
		_spec.SetField(medicalsurgery.FieldResult, field.TypeString, value)
		_node.Result = value
	}
	if value, ok := msc.mutation.Description(); ok {
		_spec.SetField(medicalsurgery.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := msc.mutation.Fee(); ok {
		_spec.SetField(medicalsurgery.FieldFee, field.TypeFloat64, value)
		_node.Fee = value
	}
	if value, ok := msc.mutation.MainDoctorID(); ok {
		_spec.SetField(medicalsurgery.FieldMainDoctorID, field.TypeUUID, value)
		_node.MainDoctorID = value
	}
	if value, ok := msc.mutation.SupportDoctorIds(); ok {
		_spec.SetField(medicalsurgery.FieldSupportDoctorIds, field.TypeString, value)
		_node.SupportDoctorIds = &value
	}
	if value, ok := msc.mutation.SupportNurseIds(); ok {
		_spec.SetField(medicalsurgery.FieldSupportNurseIds, field.TypeString, value)
		_node.SupportNurseIds = &value
	}
	if value, ok := msc.mutation.CreatedAt(); ok {
		_spec.SetField(medicalsurgery.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := msc.mutation.CreatedBy(); ok {
		_spec.SetField(medicalsurgery.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = value
	}
	if value, ok := msc.mutation.UpdatedBy(); ok {
		_spec.SetField(medicalsurgery.FieldUpdatedBy, field.TypeUUID, value)
		_node.UpdatedBy = value
	}
	if value, ok := msc.mutation.UpdatedAt(); ok {
		_spec.SetField(medicalsurgery.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := msc.mutation.MedicalHistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   medicalsurgery.MedicalHistoriesTable,
			Columns: []string{medicalsurgery.MedicalHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(medicalhistories.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MedicalHistoryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MedicalSurgery.Create().
//		SetMedicalHistoryID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MedicalSurgeryUpsert) {
//			SetMedicalHistoryID(v+v).
//		}).
//		Exec(ctx)
func (msc *MedicalSurgeryCreate) OnConflict(opts ...sql.ConflictOption) *MedicalSurgeryUpsertOne {
	msc.conflict = opts
	return &MedicalSurgeryUpsertOne{
		create: msc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MedicalSurgery.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (msc *MedicalSurgeryCreate) OnConflictColumns(columns ...string) *MedicalSurgeryUpsertOne {
	msc.conflict = append(msc.conflict, sql.ConflictColumns(columns...))
	return &MedicalSurgeryUpsertOne{
		create: msc,
	}
}

type (
	// MedicalSurgeryUpsertOne is the builder for "upsert"-ing
	//  one MedicalSurgery node.
	MedicalSurgeryUpsertOne struct {
		create *MedicalSurgeryCreate
	}

	// MedicalSurgeryUpsert is the "OnConflict" setter.
	MedicalSurgeryUpsert struct {
		*sql.UpdateSet
	}
)

// SetMedicalHistoryID sets the "medical_history_id" field.
func (u *MedicalSurgeryUpsert) SetMedicalHistoryID(v uuid.UUID) *MedicalSurgeryUpsert {
	u.Set(medicalsurgery.FieldMedicalHistoryID, v)
	return u
}

// UpdateMedicalHistoryID sets the "medical_history_id" field to the value that was provided on create.
func (u *MedicalSurgeryUpsert) UpdateMedicalHistoryID() *MedicalSurgeryUpsert {
	u.SetExcluded(medicalsurgery.FieldMedicalHistoryID)
	return u
}

// SetStartDate sets the "start_date" field.
func (u *MedicalSurgeryUpsert) SetStartDate(v time.Time) *MedicalSurgeryUpsert {
	u.Set(medicalsurgery.FieldStartDate, v)
	return u
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *MedicalSurgeryUpsert) UpdateStartDate() *MedicalSurgeryUpsert {
	u.SetExcluded(medicalsurgery.FieldStartDate)
	return u
}

// SetEndDate sets the "end_date" field.
func (u *MedicalSurgeryUpsert) SetEndDate(v time.Time) *MedicalSurgeryUpsert {
	u.Set(medicalsurgery.FieldEndDate, v)
	return u
}

// UpdateEndDate sets the "end_date" field to the value that was provided on create.
func (u *MedicalSurgeryUpsert) UpdateEndDate() *MedicalSurgeryUpsert {
	u.SetExcluded(medicalsurgery.FieldEndDate)
	return u
}

// SetName sets the "name" field.
func (u *MedicalSurgeryUpsert) SetName(v string) *MedicalSurgeryUpsert {
	u.Set(medicalsurgery.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MedicalSurgeryUpsert) UpdateName() *MedicalSurgeryUpsert {
	u.SetExcluded(medicalsurgery.FieldName)
	return u
}

// SetResult sets the "result" field.
func (u *MedicalSurgeryUpsert) SetResult(v string) *MedicalSurgeryUpsert {
	u.Set(medicalsurgery.FieldResult, v)
	return u
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *MedicalSurgeryUpsert) UpdateResult() *MedicalSurgeryUpsert {
	u.SetExcluded(medicalsurgery.FieldResult)
	return u
}

// SetDescription sets the "description" field.
func (u *MedicalSurgeryUpsert) SetDescription(v string) *MedicalSurgeryUpsert {
	u.Set(medicalsurgery.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MedicalSurgeryUpsert) UpdateDescription() *MedicalSurgeryUpsert {
	u.SetExcluded(medicalsurgery.FieldDescription)
	return u
}

// SetFee sets the "fee" field.
func (u *MedicalSurgeryUpsert) SetFee(v float64) *MedicalSurgeryUpsert {
	u.Set(medicalsurgery.FieldFee, v)
	return u
}

// UpdateFee sets the "fee" field to the value that was provided on create.
func (u *MedicalSurgeryUpsert) UpdateFee() *MedicalSurgeryUpsert {
	u.SetExcluded(medicalsurgery.FieldFee)
	return u
}

// AddFee adds v to the "fee" field.
func (u *MedicalSurgeryUpsert) AddFee(v float64) *MedicalSurgeryUpsert {
	u.Add(medicalsurgery.FieldFee, v)
	return u
}

// SetMainDoctorID sets the "main_doctor_id" field.
func (u *MedicalSurgeryUpsert) SetMainDoctorID(v uuid.UUID) *MedicalSurgeryUpsert {
	u.Set(medicalsurgery.FieldMainDoctorID, v)
	return u
}

// UpdateMainDoctorID sets the "main_doctor_id" field to the value that was provided on create.
func (u *MedicalSurgeryUpsert) UpdateMainDoctorID() *MedicalSurgeryUpsert {
	u.SetExcluded(medicalsurgery.FieldMainDoctorID)
	return u
}

// SetSupportDoctorIds sets the "support_doctor_ids" field.
func (u *MedicalSurgeryUpsert) SetSupportDoctorIds(v string) *MedicalSurgeryUpsert {
	u.Set(medicalsurgery.FieldSupportDoctorIds, v)
	return u
}

// UpdateSupportDoctorIds sets the "support_doctor_ids" field to the value that was provided on create.
func (u *MedicalSurgeryUpsert) UpdateSupportDoctorIds() *MedicalSurgeryUpsert {
	u.SetExcluded(medicalsurgery.FieldSupportDoctorIds)
	return u
}

// SetSupportNurseIds sets the "support_nurse_ids" field.
func (u *MedicalSurgeryUpsert) SetSupportNurseIds(v string) *MedicalSurgeryUpsert {
	u.Set(medicalsurgery.FieldSupportNurseIds, v)
	return u
}

// UpdateSupportNurseIds sets the "support_nurse_ids" field to the value that was provided on create.
func (u *MedicalSurgeryUpsert) UpdateSupportNurseIds() *MedicalSurgeryUpsert {
	u.SetExcluded(medicalsurgery.FieldSupportNurseIds)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *MedicalSurgeryUpsert) SetCreatedAt(v time.Time) *MedicalSurgeryUpsert {
	u.Set(medicalsurgery.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MedicalSurgeryUpsert) UpdateCreatedAt() *MedicalSurgeryUpsert {
	u.SetExcluded(medicalsurgery.FieldCreatedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *MedicalSurgeryUpsert) SetCreatedBy(v uuid.UUID) *MedicalSurgeryUpsert {
	u.Set(medicalsurgery.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *MedicalSurgeryUpsert) UpdateCreatedBy() *MedicalSurgeryUpsert {
	u.SetExcluded(medicalsurgery.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *MedicalSurgeryUpsert) SetUpdatedBy(v uuid.UUID) *MedicalSurgeryUpsert {
	u.Set(medicalsurgery.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *MedicalSurgeryUpsert) UpdateUpdatedBy() *MedicalSurgeryUpsert {
	u.SetExcluded(medicalsurgery.FieldUpdatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MedicalSurgeryUpsert) SetUpdatedAt(v time.Time) *MedicalSurgeryUpsert {
	u.Set(medicalsurgery.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MedicalSurgeryUpsert) UpdateUpdatedAt() *MedicalSurgeryUpsert {
	u.SetExcluded(medicalsurgery.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.MedicalSurgery.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(medicalsurgery.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MedicalSurgeryUpsertOne) UpdateNewValues() *MedicalSurgeryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(medicalsurgery.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MedicalSurgery.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MedicalSurgeryUpsertOne) Ignore() *MedicalSurgeryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MedicalSurgeryUpsertOne) DoNothing() *MedicalSurgeryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MedicalSurgeryCreate.OnConflict
// documentation for more info.
func (u *MedicalSurgeryUpsertOne) Update(set func(*MedicalSurgeryUpsert)) *MedicalSurgeryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MedicalSurgeryUpsert{UpdateSet: update})
	}))
	return u
}

// SetMedicalHistoryID sets the "medical_history_id" field.
func (u *MedicalSurgeryUpsertOne) SetMedicalHistoryID(v uuid.UUID) *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetMedicalHistoryID(v)
	})
}

// UpdateMedicalHistoryID sets the "medical_history_id" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertOne) UpdateMedicalHistoryID() *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateMedicalHistoryID()
	})
}

// SetStartDate sets the "start_date" field.
func (u *MedicalSurgeryUpsertOne) SetStartDate(v time.Time) *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetStartDate(v)
	})
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertOne) UpdateStartDate() *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateStartDate()
	})
}

// SetEndDate sets the "end_date" field.
func (u *MedicalSurgeryUpsertOne) SetEndDate(v time.Time) *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetEndDate(v)
	})
}

// UpdateEndDate sets the "end_date" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertOne) UpdateEndDate() *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateEndDate()
	})
}

// SetName sets the "name" field.
func (u *MedicalSurgeryUpsertOne) SetName(v string) *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertOne) UpdateName() *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateName()
	})
}

// SetResult sets the "result" field.
func (u *MedicalSurgeryUpsertOne) SetResult(v string) *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertOne) UpdateResult() *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateResult()
	})
}

// SetDescription sets the "description" field.
func (u *MedicalSurgeryUpsertOne) SetDescription(v string) *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertOne) UpdateDescription() *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateDescription()
	})
}

// SetFee sets the "fee" field.
func (u *MedicalSurgeryUpsertOne) SetFee(v float64) *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetFee(v)
	})
}

// AddFee adds v to the "fee" field.
func (u *MedicalSurgeryUpsertOne) AddFee(v float64) *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.AddFee(v)
	})
}

// UpdateFee sets the "fee" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertOne) UpdateFee() *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateFee()
	})
}

// SetMainDoctorID sets the "main_doctor_id" field.
func (u *MedicalSurgeryUpsertOne) SetMainDoctorID(v uuid.UUID) *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetMainDoctorID(v)
	})
}

// UpdateMainDoctorID sets the "main_doctor_id" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertOne) UpdateMainDoctorID() *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateMainDoctorID()
	})
}

// SetSupportDoctorIds sets the "support_doctor_ids" field.
func (u *MedicalSurgeryUpsertOne) SetSupportDoctorIds(v string) *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetSupportDoctorIds(v)
	})
}

// UpdateSupportDoctorIds sets the "support_doctor_ids" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertOne) UpdateSupportDoctorIds() *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateSupportDoctorIds()
	})
}

// SetSupportNurseIds sets the "support_nurse_ids" field.
func (u *MedicalSurgeryUpsertOne) SetSupportNurseIds(v string) *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetSupportNurseIds(v)
	})
}

// UpdateSupportNurseIds sets the "support_nurse_ids" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertOne) UpdateSupportNurseIds() *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateSupportNurseIds()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *MedicalSurgeryUpsertOne) SetCreatedAt(v time.Time) *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertOne) UpdateCreatedAt() *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *MedicalSurgeryUpsertOne) SetCreatedBy(v uuid.UUID) *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertOne) UpdateCreatedBy() *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *MedicalSurgeryUpsertOne) SetUpdatedBy(v uuid.UUID) *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertOne) UpdateUpdatedBy() *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MedicalSurgeryUpsertOne) SetUpdatedAt(v time.Time) *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertOne) UpdateUpdatedAt() *MedicalSurgeryUpsertOne {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *MedicalSurgeryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MedicalSurgeryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MedicalSurgeryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MedicalSurgeryUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: MedicalSurgeryUpsertOne.ID is not supported by MySQL driver. Use MedicalSurgeryUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MedicalSurgeryUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MedicalSurgeryCreateBulk is the builder for creating many MedicalSurgery entities in bulk.
type MedicalSurgeryCreateBulk struct {
	config
	err      error
	builders []*MedicalSurgeryCreate
	conflict []sql.ConflictOption
}

// Save creates the MedicalSurgery entities in the database.
func (mscb *MedicalSurgeryCreateBulk) Save(ctx context.Context) ([]*MedicalSurgery, error) {
	if mscb.err != nil {
		return nil, mscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mscb.builders))
	nodes := make([]*MedicalSurgery, len(mscb.builders))
	mutators := make([]Mutator, len(mscb.builders))
	for i := range mscb.builders {
		func(i int, root context.Context) {
			builder := mscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MedicalSurgeryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = mscb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mscb *MedicalSurgeryCreateBulk) SaveX(ctx context.Context) []*MedicalSurgery {
	v, err := mscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mscb *MedicalSurgeryCreateBulk) Exec(ctx context.Context) error {
	_, err := mscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mscb *MedicalSurgeryCreateBulk) ExecX(ctx context.Context) {
	if err := mscb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MedicalSurgery.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MedicalSurgeryUpsert) {
//			SetMedicalHistoryID(v+v).
//		}).
//		Exec(ctx)
func (mscb *MedicalSurgeryCreateBulk) OnConflict(opts ...sql.ConflictOption) *MedicalSurgeryUpsertBulk {
	mscb.conflict = opts
	return &MedicalSurgeryUpsertBulk{
		create: mscb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MedicalSurgery.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mscb *MedicalSurgeryCreateBulk) OnConflictColumns(columns ...string) *MedicalSurgeryUpsertBulk {
	mscb.conflict = append(mscb.conflict, sql.ConflictColumns(columns...))
	return &MedicalSurgeryUpsertBulk{
		create: mscb,
	}
}

// MedicalSurgeryUpsertBulk is the builder for "upsert"-ing
// a bulk of MedicalSurgery nodes.
type MedicalSurgeryUpsertBulk struct {
	create *MedicalSurgeryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MedicalSurgery.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(medicalsurgery.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MedicalSurgeryUpsertBulk) UpdateNewValues() *MedicalSurgeryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(medicalsurgery.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MedicalSurgery.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MedicalSurgeryUpsertBulk) Ignore() *MedicalSurgeryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MedicalSurgeryUpsertBulk) DoNothing() *MedicalSurgeryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MedicalSurgeryCreateBulk.OnConflict
// documentation for more info.
func (u *MedicalSurgeryUpsertBulk) Update(set func(*MedicalSurgeryUpsert)) *MedicalSurgeryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MedicalSurgeryUpsert{UpdateSet: update})
	}))
	return u
}

// SetMedicalHistoryID sets the "medical_history_id" field.
func (u *MedicalSurgeryUpsertBulk) SetMedicalHistoryID(v uuid.UUID) *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetMedicalHistoryID(v)
	})
}

// UpdateMedicalHistoryID sets the "medical_history_id" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertBulk) UpdateMedicalHistoryID() *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateMedicalHistoryID()
	})
}

// SetStartDate sets the "start_date" field.
func (u *MedicalSurgeryUpsertBulk) SetStartDate(v time.Time) *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetStartDate(v)
	})
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertBulk) UpdateStartDate() *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateStartDate()
	})
}

// SetEndDate sets the "end_date" field.
func (u *MedicalSurgeryUpsertBulk) SetEndDate(v time.Time) *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetEndDate(v)
	})
}

// UpdateEndDate sets the "end_date" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertBulk) UpdateEndDate() *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateEndDate()
	})
}

// SetName sets the "name" field.
func (u *MedicalSurgeryUpsertBulk) SetName(v string) *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertBulk) UpdateName() *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateName()
	})
}

// SetResult sets the "result" field.
func (u *MedicalSurgeryUpsertBulk) SetResult(v string) *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertBulk) UpdateResult() *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateResult()
	})
}

// SetDescription sets the "description" field.
func (u *MedicalSurgeryUpsertBulk) SetDescription(v string) *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertBulk) UpdateDescription() *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateDescription()
	})
}

// SetFee sets the "fee" field.
func (u *MedicalSurgeryUpsertBulk) SetFee(v float64) *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetFee(v)
	})
}

// AddFee adds v to the "fee" field.
func (u *MedicalSurgeryUpsertBulk) AddFee(v float64) *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.AddFee(v)
	})
}

// UpdateFee sets the "fee" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertBulk) UpdateFee() *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateFee()
	})
}

// SetMainDoctorID sets the "main_doctor_id" field.
func (u *MedicalSurgeryUpsertBulk) SetMainDoctorID(v uuid.UUID) *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetMainDoctorID(v)
	})
}

// UpdateMainDoctorID sets the "main_doctor_id" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertBulk) UpdateMainDoctorID() *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateMainDoctorID()
	})
}

// SetSupportDoctorIds sets the "support_doctor_ids" field.
func (u *MedicalSurgeryUpsertBulk) SetSupportDoctorIds(v string) *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetSupportDoctorIds(v)
	})
}

// UpdateSupportDoctorIds sets the "support_doctor_ids" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertBulk) UpdateSupportDoctorIds() *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateSupportDoctorIds()
	})
}

// SetSupportNurseIds sets the "support_nurse_ids" field.
func (u *MedicalSurgeryUpsertBulk) SetSupportNurseIds(v string) *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetSupportNurseIds(v)
	})
}

// UpdateSupportNurseIds sets the "support_nurse_ids" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertBulk) UpdateSupportNurseIds() *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateSupportNurseIds()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *MedicalSurgeryUpsertBulk) SetCreatedAt(v time.Time) *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertBulk) UpdateCreatedAt() *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *MedicalSurgeryUpsertBulk) SetCreatedBy(v uuid.UUID) *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertBulk) UpdateCreatedBy() *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *MedicalSurgeryUpsertBulk) SetUpdatedBy(v uuid.UUID) *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertBulk) UpdateUpdatedBy() *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MedicalSurgeryUpsertBulk) SetUpdatedAt(v time.Time) *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MedicalSurgeryUpsertBulk) UpdateUpdatedAt() *MedicalSurgeryUpsertBulk {
	return u.Update(func(s *MedicalSurgeryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *MedicalSurgeryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MedicalSurgeryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MedicalSurgeryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MedicalSurgeryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
