// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"patient/ent/medicaltreatment"
	"patient/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MedicalTreatmentDelete is the builder for deleting a MedicalTreatment entity.
type MedicalTreatmentDelete struct {
	config
	hooks    []Hook
	mutation *MedicalTreatmentMutation
}

// Where appends a list predicates to the MedicalTreatmentDelete builder.
func (mtd *MedicalTreatmentDelete) Where(ps ...predicate.MedicalTreatment) *MedicalTreatmentDelete {
	mtd.mutation.Where(ps...)
	return mtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mtd *MedicalTreatmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mtd.sqlExec, mtd.mutation, mtd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mtd *MedicalTreatmentDelete) ExecX(ctx context.Context) int {
	n, err := mtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mtd *MedicalTreatmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(medicaltreatment.Table, sqlgraph.NewFieldSpec(medicaltreatment.FieldID, field.TypeUUID))
	if ps := mtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mtd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mtd.mutation.done = true
	return affected, err
}

// MedicalTreatmentDeleteOne is the builder for deleting a single MedicalTreatment entity.
type MedicalTreatmentDeleteOne struct {
	mtd *MedicalTreatmentDelete
}

// Where appends a list predicates to the MedicalTreatmentDelete builder.
func (mtdo *MedicalTreatmentDeleteOne) Where(ps ...predicate.MedicalTreatment) *MedicalTreatmentDeleteOne {
	mtdo.mtd.mutation.Where(ps...)
	return mtdo
}

// Exec executes the deletion query.
func (mtdo *MedicalTreatmentDeleteOne) Exec(ctx context.Context) error {
	n, err := mtdo.mtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{medicaltreatment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mtdo *MedicalTreatmentDeleteOne) ExecX(ctx context.Context) {
	if err := mtdo.Exec(ctx); err != nil {
		panic(err)
	}
}
