// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"patient/ent/outpatient"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Outpatient is the model entity for the Outpatient schema.
type Outpatient struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Outpatient) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case outpatient.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Outpatient fields.
func (o *Outpatient) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case outpatient.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			o.ID = int(value.Int64)
		default:
			o.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Outpatient.
// This includes values selected through modifiers, order, etc.
func (o *Outpatient) Value(name string) (ent.Value, error) {
	return o.selectValues.Get(name)
}

// Update returns a builder for updating this Outpatient.
// Note that you need to call Outpatient.Unwrap() before calling this method if this Outpatient
// was returned from a transaction, and the transaction was committed or rolled back.
func (o *Outpatient) Update() *OutpatientUpdateOne {
	return NewOutpatientClient(o.config).UpdateOne(o)
}

// Unwrap unwraps the Outpatient entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (o *Outpatient) Unwrap() *Outpatient {
	_tx, ok := o.config.driver.(*txDriver)
	if !ok {
		panic("ent: Outpatient is not a transactional entity")
	}
	o.config.driver = _tx.drv
	return o
}

// String implements the fmt.Stringer.
func (o *Outpatient) String() string {
	var builder strings.Builder
	builder.WriteString("Outpatient(")
	builder.WriteString(fmt.Sprintf("id=%v", o.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Outpatients is a parsable slice of Outpatient.
type Outpatients []*Outpatient
