// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"patient/ent/outpatient"
	"patient/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OutpatientDelete is the builder for deleting a Outpatient entity.
type OutpatientDelete struct {
	config
	hooks    []Hook
	mutation *OutpatientMutation
}

// Where appends a list predicates to the OutpatientDelete builder.
func (od *OutpatientDelete) Where(ps ...predicate.Outpatient) *OutpatientDelete {
	od.mutation.Where(ps...)
	return od
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (od *OutpatientDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, od.sqlExec, od.mutation, od.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (od *OutpatientDelete) ExecX(ctx context.Context) int {
	n, err := od.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (od *OutpatientDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(outpatient.Table, sqlgraph.NewFieldSpec(outpatient.FieldID, field.TypeUUID))
	if ps := od.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, od.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	od.mutation.done = true
	return affected, err
}

// OutpatientDeleteOne is the builder for deleting a single Outpatient entity.
type OutpatientDeleteOne struct {
	od *OutpatientDelete
}

// Where appends a list predicates to the OutpatientDelete builder.
func (odo *OutpatientDeleteOne) Where(ps ...predicate.Outpatient) *OutpatientDeleteOne {
	odo.od.mutation.Where(ps...)
	return odo
}

// Exec executes the deletion query.
func (odo *OutpatientDeleteOne) Exec(ctx context.Context) error {
	n, err := odo.od.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{outpatient.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (odo *OutpatientDeleteOne) ExecX(ctx context.Context) {
	if err := odo.Exec(ctx); err != nil {
		panic(err)
	}
}
