// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"patient/ent/outpatientdetail"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// OutpatientDetail is the model entity for the OutpatientDetail schema.
type OutpatientDetail struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OutpatientDetail) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case outpatientdetail.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OutpatientDetail fields.
func (od *OutpatientDetail) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case outpatientdetail.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			od.ID = int(value.Int64)
		default:
			od.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OutpatientDetail.
// This includes values selected through modifiers, order, etc.
func (od *OutpatientDetail) Value(name string) (ent.Value, error) {
	return od.selectValues.Get(name)
}

// Update returns a builder for updating this OutpatientDetail.
// Note that you need to call OutpatientDetail.Unwrap() before calling this method if this OutpatientDetail
// was returned from a transaction, and the transaction was committed or rolled back.
func (od *OutpatientDetail) Update() *OutpatientDetailUpdateOne {
	return NewOutpatientDetailClient(od.config).UpdateOne(od)
}

// Unwrap unwraps the OutpatientDetail entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (od *OutpatientDetail) Unwrap() *OutpatientDetail {
	_tx, ok := od.config.driver.(*txDriver)
	if !ok {
		panic("ent: OutpatientDetail is not a transactional entity")
	}
	od.config.driver = _tx.drv
	return od
}

// String implements the fmt.Stringer.
func (od *OutpatientDetail) String() string {
	var builder strings.Builder
	builder.WriteString("OutpatientDetail(")
	builder.WriteString(fmt.Sprintf("id=%v", od.ID))
	builder.WriteByte(')')
	return builder.String()
}

// OutpatientDetails is a parsable slice of OutpatientDetail.
type OutpatientDetails []*OutpatientDetail
