// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"patient/ent/predicate"
	"patient/ent/prescriptionmedication"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PrescriptionMedicationDelete is the builder for deleting a PrescriptionMedication entity.
type PrescriptionMedicationDelete struct {
	config
	hooks    []Hook
	mutation *PrescriptionMedicationMutation
}

// Where appends a list predicates to the PrescriptionMedicationDelete builder.
func (pmd *PrescriptionMedicationDelete) Where(ps ...predicate.PrescriptionMedication) *PrescriptionMedicationDelete {
	pmd.mutation.Where(ps...)
	return pmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pmd *PrescriptionMedicationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pmd.sqlExec, pmd.mutation, pmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pmd *PrescriptionMedicationDelete) ExecX(ctx context.Context) int {
	n, err := pmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pmd *PrescriptionMedicationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(prescriptionmedication.Table, sqlgraph.NewFieldSpec(prescriptionmedication.FieldID, field.TypeUUID))
	if ps := pmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pmd.mutation.done = true
	return affected, err
}

// PrescriptionMedicationDeleteOne is the builder for deleting a single PrescriptionMedication entity.
type PrescriptionMedicationDeleteOne struct {
	pmd *PrescriptionMedicationDelete
}

// Where appends a list predicates to the PrescriptionMedicationDelete builder.
func (pmdo *PrescriptionMedicationDeleteOne) Where(ps ...predicate.PrescriptionMedication) *PrescriptionMedicationDeleteOne {
	pmdo.pmd.mutation.Where(ps...)
	return pmdo
}

// Exec executes the deletion query.
func (pmdo *PrescriptionMedicationDeleteOne) Exec(ctx context.Context) error {
	n, err := pmdo.pmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{prescriptionmedication.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pmdo *PrescriptionMedicationDeleteOne) ExecX(ctx context.Context) {
	if err := pmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
