// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"patient/ent/predicate"
	"patient/ent/treatdetail"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TreatDetailQuery is the builder for querying TreatDetail entities.
type TreatDetailQuery struct {
	config
	ctx        *QueryContext
	order      []treatdetail.OrderOption
	inters     []Interceptor
	predicates []predicate.TreatDetail
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TreatDetailQuery builder.
func (tdq *TreatDetailQuery) Where(ps ...predicate.TreatDetail) *TreatDetailQuery {
	tdq.predicates = append(tdq.predicates, ps...)
	return tdq
}

// Limit the number of records to be returned by this query.
func (tdq *TreatDetailQuery) Limit(limit int) *TreatDetailQuery {
	tdq.ctx.Limit = &limit
	return tdq
}

// Offset to start from.
func (tdq *TreatDetailQuery) Offset(offset int) *TreatDetailQuery {
	tdq.ctx.Offset = &offset
	return tdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tdq *TreatDetailQuery) Unique(unique bool) *TreatDetailQuery {
	tdq.ctx.Unique = &unique
	return tdq
}

// Order specifies how the records should be ordered.
func (tdq *TreatDetailQuery) Order(o ...treatdetail.OrderOption) *TreatDetailQuery {
	tdq.order = append(tdq.order, o...)
	return tdq
}

// First returns the first TreatDetail entity from the query.
// Returns a *NotFoundError when no TreatDetail was found.
func (tdq *TreatDetailQuery) First(ctx context.Context) (*TreatDetail, error) {
	nodes, err := tdq.Limit(1).All(setContextOp(ctx, tdq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{treatdetail.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tdq *TreatDetailQuery) FirstX(ctx context.Context) *TreatDetail {
	node, err := tdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TreatDetail ID from the query.
// Returns a *NotFoundError when no TreatDetail ID was found.
func (tdq *TreatDetailQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tdq.Limit(1).IDs(setContextOp(ctx, tdq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{treatdetail.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tdq *TreatDetailQuery) FirstIDX(ctx context.Context) int {
	id, err := tdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TreatDetail entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TreatDetail entity is found.
// Returns a *NotFoundError when no TreatDetail entities are found.
func (tdq *TreatDetailQuery) Only(ctx context.Context) (*TreatDetail, error) {
	nodes, err := tdq.Limit(2).All(setContextOp(ctx, tdq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{treatdetail.Label}
	default:
		return nil, &NotSingularError{treatdetail.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tdq *TreatDetailQuery) OnlyX(ctx context.Context) *TreatDetail {
	node, err := tdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TreatDetail ID in the query.
// Returns a *NotSingularError when more than one TreatDetail ID is found.
// Returns a *NotFoundError when no entities are found.
func (tdq *TreatDetailQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tdq.Limit(2).IDs(setContextOp(ctx, tdq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{treatdetail.Label}
	default:
		err = &NotSingularError{treatdetail.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tdq *TreatDetailQuery) OnlyIDX(ctx context.Context) int {
	id, err := tdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TreatDetails.
func (tdq *TreatDetailQuery) All(ctx context.Context) ([]*TreatDetail, error) {
	ctx = setContextOp(ctx, tdq.ctx, ent.OpQueryAll)
	if err := tdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TreatDetail, *TreatDetailQuery]()
	return withInterceptors[[]*TreatDetail](ctx, tdq, qr, tdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tdq *TreatDetailQuery) AllX(ctx context.Context) []*TreatDetail {
	nodes, err := tdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TreatDetail IDs.
func (tdq *TreatDetailQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tdq.ctx.Unique == nil && tdq.path != nil {
		tdq.Unique(true)
	}
	ctx = setContextOp(ctx, tdq.ctx, ent.OpQueryIDs)
	if err = tdq.Select(treatdetail.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tdq *TreatDetailQuery) IDsX(ctx context.Context) []int {
	ids, err := tdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tdq *TreatDetailQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tdq.ctx, ent.OpQueryCount)
	if err := tdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tdq, querierCount[*TreatDetailQuery](), tdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tdq *TreatDetailQuery) CountX(ctx context.Context) int {
	count, err := tdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tdq *TreatDetailQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tdq.ctx, ent.OpQueryExist)
	switch _, err := tdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tdq *TreatDetailQuery) ExistX(ctx context.Context) bool {
	exist, err := tdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TreatDetailQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tdq *TreatDetailQuery) Clone() *TreatDetailQuery {
	if tdq == nil {
		return nil
	}
	return &TreatDetailQuery{
		config:     tdq.config,
		ctx:        tdq.ctx.Clone(),
		order:      append([]treatdetail.OrderOption{}, tdq.order...),
		inters:     append([]Interceptor{}, tdq.inters...),
		predicates: append([]predicate.TreatDetail{}, tdq.predicates...),
		// clone intermediate query.
		sql:  tdq.sql.Clone(),
		path: tdq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (tdq *TreatDetailQuery) GroupBy(field string, fields ...string) *TreatDetailGroupBy {
	tdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TreatDetailGroupBy{build: tdq}
	grbuild.flds = &tdq.ctx.Fields
	grbuild.label = treatdetail.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (tdq *TreatDetailQuery) Select(fields ...string) *TreatDetailSelect {
	tdq.ctx.Fields = append(tdq.ctx.Fields, fields...)
	sbuild := &TreatDetailSelect{TreatDetailQuery: tdq}
	sbuild.label = treatdetail.Label
	sbuild.flds, sbuild.scan = &tdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TreatDetailSelect configured with the given aggregations.
func (tdq *TreatDetailQuery) Aggregate(fns ...AggregateFunc) *TreatDetailSelect {
	return tdq.Select().Aggregate(fns...)
}

func (tdq *TreatDetailQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tdq); err != nil {
				return err
			}
		}
	}
	for _, f := range tdq.ctx.Fields {
		if !treatdetail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tdq.path != nil {
		prev, err := tdq.path(ctx)
		if err != nil {
			return err
		}
		tdq.sql = prev
	}
	return nil
}

func (tdq *TreatDetailQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TreatDetail, error) {
	var (
		nodes = []*TreatDetail{}
		_spec = tdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TreatDetail).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TreatDetail{config: tdq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tdq *TreatDetailQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tdq.querySpec()
	_spec.Node.Columns = tdq.ctx.Fields
	if len(tdq.ctx.Fields) > 0 {
		_spec.Unique = tdq.ctx.Unique != nil && *tdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tdq.driver, _spec)
}

func (tdq *TreatDetailQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(treatdetail.Table, treatdetail.Columns, sqlgraph.NewFieldSpec(treatdetail.FieldID, field.TypeInt))
	_spec.From = tdq.sql
	if unique := tdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tdq.path != nil {
		_spec.Unique = true
	}
	if fields := tdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, treatdetail.FieldID)
		for i := range fields {
			if fields[i] != treatdetail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tdq *TreatDetailQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tdq.driver.Dialect())
	t1 := builder.Table(treatdetail.Table)
	columns := tdq.ctx.Fields
	if len(columns) == 0 {
		columns = treatdetail.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tdq.sql != nil {
		selector = tdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tdq.ctx.Unique != nil && *tdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tdq.predicates {
		p(selector)
	}
	for _, p := range tdq.order {
		p(selector)
	}
	if offset := tdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TreatDetailGroupBy is the group-by builder for TreatDetail entities.
type TreatDetailGroupBy struct {
	selector
	build *TreatDetailQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tdgb *TreatDetailGroupBy) Aggregate(fns ...AggregateFunc) *TreatDetailGroupBy {
	tdgb.fns = append(tdgb.fns, fns...)
	return tdgb
}

// Scan applies the selector query and scans the result into the given value.
func (tdgb *TreatDetailGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tdgb.build.ctx, ent.OpQueryGroupBy)
	if err := tdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TreatDetailQuery, *TreatDetailGroupBy](ctx, tdgb.build, tdgb, tdgb.build.inters, v)
}

func (tdgb *TreatDetailGroupBy) sqlScan(ctx context.Context, root *TreatDetailQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tdgb.fns))
	for _, fn := range tdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tdgb.flds)+len(tdgb.fns))
		for _, f := range *tdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TreatDetailSelect is the builder for selecting fields of TreatDetail entities.
type TreatDetailSelect struct {
	*TreatDetailQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tds *TreatDetailSelect) Aggregate(fns ...AggregateFunc) *TreatDetailSelect {
	tds.fns = append(tds.fns, fns...)
	return tds
}

// Scan applies the selector query and scans the result into the given value.
func (tds *TreatDetailSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tds.ctx, ent.OpQuerySelect)
	if err := tds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TreatDetailQuery, *TreatDetailSelect](ctx, tds.TreatDetailQuery, tds, tds.inters, v)
}

func (tds *TreatDetailSelect) sqlScan(ctx context.Context, root *TreatDetailQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tds.fns))
	for _, fn := range tds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
